"""Initial schema — 53 tables.

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-23

Covers every table required by the SRS functional requirements and development
steps; see documentation/REQUIREMENTS_COVERAGE.md for the clause-by-clause map.

Dialect notes
-------------
* PostgreSQL extensions (pgcrypto, pg_trgm, vector) are created first because
  the ``chunks.embedding`` column needs the ``vector`` type to exist.
* ``JSONType`` renders as JSONB on PostgreSQL and JSON on SQLite; ``Vector``
  renders as pgvector on PostgreSQL and a JSON float array elsewhere.  Both are
  defined in ``src/db/base.py`` and rendered here via the ``render_item`` hook
  in ``alembic/env.py``.
* The trigram / full-text / ANN indexes at the end are PostgreSQL-only and are
  skipped on SQLite, where the test suite runs.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from src.db.base import JSONType, TZDateTime, Vector
revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# PostgreSQL extensions must exist before any table that uses their types.
POSTGRES_EXTENSIONS = (
    "CREATE EXTENSION IF NOT EXISTS pgcrypto",
    "CREATE EXTENSION IF NOT EXISTS pg_trgm",
    "CREATE EXTENSION IF NOT EXISTS vector",
)

# Search / similarity indexes that have no portable SQLAlchemy equivalent.
POSTGRES_INDEXES = (
    # FR lvi - near-duplicate complaint detection (SRS Step 52)
    "CREATE INDEX IF NOT EXISTS ix_comp_desc_trgm "
    "ON complaints USING gin (description_clean gin_trgm_ops)",
    # FR lxxi - complaint free-text search
    "CREATE INDEX IF NOT EXISTS ix_comp_fts ON complaints USING gin ("
    "to_tsvector('english', coalesce(title,'') || ' ' || coalesce(description_clean,'')))",
    # Lexical half of hybrid retrieval (SRS Step 25)
    "CREATE INDEX IF NOT EXISTS ix_chunks_fts "
    "ON chunks USING gin (to_tsvector('english', text))",
    # Semantic half of hybrid retrieval
    "CREATE INDEX IF NOT EXISTS ix_chunks_embedding "
    "ON chunks USING ivfflat (embedding vector_cosine_ops) WITH (lists = 50)",
)

POSTGRES_DROP_INDEXES = tuple(
    f"DROP INDEX IF EXISTS {name}"
    for name in ("ix_chunks_embedding", "ix_chunks_fts", "ix_comp_fts", "ix_comp_desc_trgm")
)


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def upgrade() -> None:
    if _is_postgres():
        for statement in POSTGRES_EXTENSIONS:
            op.execute(statement)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('code', name=op.f('uq_departments_code'))
    )
    op.create_table('escalation_levels',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_escalation_levels')),
    sa.UniqueConstraint('rank', name=op.f('uq_escalation_levels_rank'))
    )
    op.create_table('injection_patterns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pattern', sa.String(length=512), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("severity IN ('CRITICAL', 'HIGH', 'MEDIUM', 'INFORMATIONAL')", name=op.f('ck_injection_patterns_severity_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_injection_patterns'))
    )
    op.create_table('lexicon_terms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('signal_key', sa.String(length=64), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('match_type', sa.String(length=16), nullable=False),
    sa.Column('weight', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("match_type IN ('PHRASE','REGEX','WORD')", name=op.f('ck_lexicon_terms_match_type_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lexicon_terms')),
    sa.UniqueConstraint('signal_key', 'term', name='uq_lexicon_signal_term')
    )
    with op.batch_alter_table('lexicon_terms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lexicon_terms_signal_key'), ['signal_key'], unique=False)

    op.create_table('llm_cache',
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('response_raw', sa.Text(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('prompt_hash', name=op.f('pk_llm_cache'))
    )
    op.create_table('priority_levels',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_priority_levels')),
    sa.UniqueConstraint('rank', name=op.f('uq_priority_levels_rank'))
    )
    op.create_table('promise_patterns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pattern', sa.String(length=512), nullable=False),
    sa.Column('promise_type', sa.String(length=64), nullable=False),
    sa.Column('requires_action', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promise_patterns'))
    )
    op.create_table('prompt_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_versions')),
    sa.UniqueConstraint('name', 'version', name='uq_prompt_name_version')
    )
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.create_index('ux_prompt_one_active', ['name'], unique=True, postgresql_where=sa.text('is_active = true'), sqlite_where=sa.text('is_active = 1'))

    op.create_table('trend_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('period_type', sa.String(length=16), nullable=False),
    sa.Column('period_start', TZDateTime(), nullable=False),
    sa.Column('period_end', TZDateTime(), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('dimension', sa.String(length=64), nullable=False),
    sa.Column('dimension_value', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('previous_value', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('delta_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("direction IN ('UP', 'DOWN', 'FLAT')", name=op.f('ck_trend_snapshots_direction_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trend_snapshots')),
    sa.UniqueConstraint('period_type', 'period_start', 'metric', 'dimension', 'dimension_value', name='uq_trend_period_metric_dim')
    )
    with op.batch_alter_table('trend_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_trend_metric_period', ['metric', 'period_start'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_department_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['default_department_id'], ['departments.id'], name=op.f('fk_categories_default_department_id_departments'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('code', name=op.f('uq_categories_code'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', TZDateTime(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('customer', 'agent', 'reviewer', 'manager', 'admin', 'evaluator')", name=op.f('ck_users_role_valid')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_users_department_id_departments'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('app_config',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', JSONType, nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', TZDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_app_config_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_config'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('before', JSONType, nullable=True),
    sa.Column('after', JSONType, nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_log_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_actor', ['actor_id', 'created_at'], unique=False)
        batch_op.create_index('ix_audit_entity', ['entity_type', 'entity_id', 'created_at'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_ref', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("tier IN ('STANDARD', 'PREMIUM', 'VIP', 'BUSINESS')", name=op.f('ck_customers_tier_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_customers_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('external_ref', name=op.f('uq_customers_external_ref'))
    )
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("doc_type IN ('POLICY', 'SOP', 'FAQ', 'ROUTING_RULES', 'ESCALATION', 'SLA', 'COMPLIANCE', 'HANDBOOK', 'PROCESS', 'OTHER')", name=op.f('ck_documents_doc_type_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_documents_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_documents_department_id_departments'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('family_key', name=op.f('uq_documents_family_key'))
    )
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload', JSONType, nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('result', JSONType, nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('started_at', TZDateTime(), nullable=True),
    sa.Column('finished_at', TZDateTime(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('QUEUED', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED')", name=op.f('ck_jobs_status_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_jobs_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_jobs_type', ['job_type'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', TZDateTime(), nullable=False),
    sa.Column('revoked_at', TZDateTime(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('report_exports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_type', sa.String(length=64), nullable=False),
    sa.Column('format', sa.String(length=8), nullable=False),
    sa.Column('filters', JSONType, nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("format IN ('CSV', 'PDF', 'XLSX')", name=op.f('ck_report_exports_format_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_report_exports_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_exports'))
    )
    op.create_table('sla_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('priority_code', sa.String(length=8), nullable=False),
    sa.Column('first_response_mins', sa.Integer(), nullable=False),
    sa.Column('resolution_mins', sa.Integer(), nullable=False),
    sa.Column('risk_threshold_pct', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_sla_policies_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['priority_code'], ['priority_levels.code'], name=op.f('fk_sla_policies_priority_code_priority_levels')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sla_policies')),
    sa.UniqueConstraint('category_id', 'priority_code', name='uq_sla_category_priority')
    )
    op.create_table('subcategories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_subcategories_category_id_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subcategories')),
    sa.UniqueConstraint('category_id', 'code', name='uq_subcat_category_code')
    )
    op.create_table('benchmark_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('dataset_tag', sa.String(length=64), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('ruleset_version', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('metrics', JSONType, nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('finished_at', TZDateTime(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_benchmark_runs_job_id_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benchmark_runs'))
    )
    op.create_table('complaints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('public_ref', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('submitted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description_raw', sa.Text(), nullable=False),
    sa.Column('description_clean', sa.Text(), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=True),
    sa.Column('order_ref', sa.String(length=64), nullable=True),
    sa.Column('transaction_ref', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('customer_type', sa.String(length=32), nullable=True),
    sa.Column('preferred_contact', sa.String(length=32), nullable=True),
    sa.Column('requested_resolution', sa.Text(), nullable=True),
    sa.Column('previous_complaint_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('subcategory_id', sa.Uuid(), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('support_department_id', sa.Uuid(), nullable=True),
    sa.Column('urgency', sa.String(length=16), nullable=True),
    sa.Column('priority_code', sa.String(length=8), nullable=True),
    sa.Column('escalation_code', sa.String(length=64), nullable=True),
    sa.Column('sentiment', sa.String(length=24), nullable=True),
    sa.Column('verification_outcome', sa.String(length=32), nullable=True),
    sa.Column('primary_issue', sa.String(length=255), nullable=True),
    sa.Column('secondary_issue', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('emotion_indicators', JSONType, nullable=False),
    sa.Column('injection_suspected', sa.Boolean(), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('repeat_count', sa.Integer(), nullable=False),
    sa.Column('missing_information', JSONType, nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('expected_category_code', sa.String(length=64), nullable=True),
    sa.Column('expected_subcategory_code', sa.String(length=64), nullable=True),
    sa.Column('expected_department_code', sa.String(length=64), nullable=True),
    sa.Column('expected_urgency', sa.String(length=16), nullable=True),
    sa.Column('expected_priority_code', sa.String(length=8), nullable=True),
    sa.Column('expected_escalation_code', sa.String(length=64), nullable=True),
    sa.Column('dataset_tag', sa.String(length=64), nullable=True),
    sa.Column('analyzed_at', TZDateTime(), nullable=True),
    sa.Column('validated_at', TZDateTime(), nullable=True),
    sa.Column('first_response_at', TZDateTime(), nullable=True),
    sa.Column('resolved_at', TZDateTime(), nullable=True),
    sa.Column('closed_at', TZDateTime(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("channel IN ('WEB', 'EMAIL', 'CHAT', 'PHONE', 'UPLOAD', 'IMPORT')", name=op.f('ck_complaints_channel_valid')),
    sa.CheckConstraint("sentiment IN ('POSITIVE', 'NEUTRAL', 'NEGATIVE', 'STRONGLY_NEGATIVE')", name=op.f('ck_complaints_sentiment_valid')),
    sa.CheckConstraint("status IN ('NEW', 'ANALYZING', 'ANALYZED', 'VALIDATED', 'ASSIGNED', 'IN_PROGRESS', 'AWAITING_CUSTOMER', 'ESCALATED', 'MANUAL_REVIEW', 'RESOLVED', 'CLOSED', 'REOPENED', 'FAILED')", name=op.f('ck_complaints_status_valid')),
    sa.CheckConstraint("urgency IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name=op.f('ck_complaints_urgency_valid')),
    sa.CheckConstraint("verification_outcome IN ('VERIFIED', 'VERIFIED_WITH_WARNING', 'CORRECTED_BY_RULES', 'MANUAL_REVIEW_REQUIRED', 'BLOCKED', 'INCOMPLETE')", name=op.f('ck_complaints_verification_outcome_valid')),
    sa.CheckConstraint('id <> previous_complaint_id', name=op.f('ck_complaints_no_self_reference')),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_complaints_assigned_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_complaints_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_complaints_customer_id_customers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_complaints_department_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['escalation_code'], ['escalation_levels.code'], name=op.f('fk_complaints_escalation_code_escalation_levels'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['previous_complaint_id'], ['complaints.id'], name=op.f('fk_complaints_previous_complaint_id_complaints'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['priority_code'], ['priority_levels.code'], name=op.f('fk_complaints_priority_code_priority_levels'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], name=op.f('fk_complaints_subcategory_id_subcategories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], name=op.f('fk_complaints_submitted_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['support_department_id'], ['departments.id'], name=op.f('fk_complaints_support_department_id_departments'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaints')),
    sa.UniqueConstraint('public_ref', name=op.f('uq_complaints_public_ref'))
    )
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.create_index('ix_comp_assigned', ['assigned_to', 'status'], unique=False)
        batch_op.create_index('ix_comp_customer', ['customer_id', 'created_at'], unique=False)
        batch_op.create_index('ix_comp_dataset', ['dataset_tag'], unique=False)
        batch_op.create_index('ix_comp_queue', ['department_id', 'priority_code', 'created_at'], unique=False)
        batch_op.create_index('ix_comp_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_order_ref'), ['order_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_verification_outcome'), ['verification_outcome'], unique=False)

    op.create_table('document_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('doc_ref', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('file_format', sa.String(length=8), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('section_count', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('parse_status', sa.String(length=32), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('metadata_json', JSONType, nullable=True),
    sa.Column('metadata_complete', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('activated_at', TZDateTime(), nullable=True),
    sa.Column('superseded_at', TZDateTime(), nullable=True),
    sa.Column('superseded_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("file_format IN ('PDF', 'DOCX', 'TXT', 'MD', 'CSV')", name=op.f('ck_document_versions_file_format_valid')),
    sa.CheckConstraint("parse_status IN ('PENDING', 'PARSING', 'PARSED', 'FAILED', 'NO_TEXT_LAYER')", name=op.f('ck_document_versions_parse_status_valid')),
    sa.CheckConstraint("status IN ('DRAFT', 'ACTIVE', 'SUPERSEDED', 'EXPIRED', 'METADATA_REVIEW')", name=op.f('ck_document_versions_status_valid')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_versions_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['document_versions.id'], name=op.f('fk_document_versions_superseded_by_id_document_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_document_versions_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_versions')),
    sa.UniqueConstraint('document_id', 'version', name='uq_docver_document_version'),
    sa.UniqueConstraint('file_hash', name='uq_docver_file_hash')
    )
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_versions_doc_ref'), ['doc_ref'], unique=False)
        batch_op.create_index('ix_docver_ref_version', ['doc_ref', 'version'], unique=False)
        batch_op.create_index('ux_docver_one_active', ['document_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"), sqlite_where=sa.text("status = 'ACTIVE'"))

    op.create_table('rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rule_ref', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('subcategory_id', sa.Uuid(), nullable=True),
    sa.Column('conditions', JSONType, nullable=False),
    sa.Column('outcome_category_id', sa.Uuid(), nullable=True),
    sa.Column('outcome_subcategory_id', sa.Uuid(), nullable=True),
    sa.Column('outcome_department_id', sa.Uuid(), nullable=True),
    sa.Column('outcome_support_department_id', sa.Uuid(), nullable=True),
    sa.Column('outcome_urgency', sa.String(length=16), nullable=True),
    sa.Column('outcome_priority_code', sa.String(length=8), nullable=True),
    sa.Column('outcome_escalation_code', sa.String(length=64), nullable=True),
    sa.Column('required_actions', JSONType, nullable=False),
    sa.Column('prohibited_actions', JSONType, nullable=False),
    sa.Column('policy_refs', JSONType, nullable=False),
    sa.Column('follow_up_required', sa.Boolean(), nullable=False),
    sa.Column('precedence', sa.Integer(), nullable=False),
    sa.Column('is_mandatory_escalation', sa.Boolean(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("outcome_urgency IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name=op.f('ck_rules_outcome_urgency_valid')),
    sa.CheckConstraint("rule_type IN ('ROUTING', 'CLASSIFICATION', 'URGENCY', 'ESCALATION', 'RESOLUTION', 'ELIGIBILITY', 'SLA')", name=op.f('ck_rules_rule_type_valid')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_rules_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_rules_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outcome_category_id'], ['categories.id'], name=op.f('fk_rules_outcome_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outcome_department_id'], ['departments.id'], name=op.f('fk_rules_outcome_department_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outcome_escalation_code'], ['escalation_levels.code'], name=op.f('fk_rules_outcome_escalation_code_escalation_levels'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outcome_priority_code'], ['priority_levels.code'], name=op.f('fk_rules_outcome_priority_code_priority_levels'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outcome_subcategory_id'], ['subcategories.id'], name=op.f('fk_rules_outcome_subcategory_id_subcategories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outcome_support_department_id'], ['departments.id'], name=op.f('fk_rules_outcome_support_department_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], name=op.f('fk_rules_subcategory_id_subcategories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rules')),
    sa.UniqueConstraint('rule_ref', name=op.f('uq_rules_rule_ref'))
    )
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.create_index('ix_rules_active_precedence', ['is_active', 'precedence'], unique=False)
        batch_op.create_index('ix_rules_mandatory', ['is_mandatory_escalation', 'is_active'], unique=False)

    op.create_table('agent_guidance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('rule_ref', sa.String(length=64), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.Uuid(), nullable=True),
    sa.Column('acknowledged_at', TZDateTime(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("kind IN ('ACTION', 'CAUTION', 'VERIFICATION', 'ESCALATION', 'INFORMATION')", name=op.f('ck_agent_guidance_kind_valid')),
    sa.CheckConstraint("source IN ('GENAI', 'RULE')", name=op.f('ck_agent_guidance_source_valid')),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], name=op.f('fk_agent_guidance_acknowledged_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_agent_guidance_complaint_id_complaints'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_guidance'))
    )
    with op.batch_alter_table('agent_guidance', schema=None) as batch_op:
        batch_op.create_index('ix_guidance_complaint', ['complaint_id', 'ordinal'], unique=False)

    op.create_table('benchmark_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('benchmark_run_id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('expected_value', sa.String(length=255), nullable=True),
    sa.Column('genai_value', sa.String(length=255), nullable=True),
    sa.Column('python_value', sa.String(length=255), nullable=True),
    sa.Column('genai_correct', sa.Boolean(), nullable=True),
    sa.Column('python_correct', sa.Boolean(), nullable=True),
    sa.Column('agreed', sa.Boolean(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_run_id'], ['benchmark_runs.id'], name=op.f('fk_benchmark_results_benchmark_run_id_benchmark_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_benchmark_results_complaint_id_complaints'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benchmark_results'))
    )
    with op.batch_alter_table('benchmark_results', schema=None) as batch_op:
        batch_op.create_index('ix_benchresults_complaint', ['complaint_id'], unique=False)
        batch_op.create_index('ix_benchresults_run_field', ['benchmark_run_id', 'field'], unique=False)

    op.create_table('complaint_attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_complaint_attachments_complaint_id_complaints'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaint_attachments'))
    )
    with op.batch_alter_table('complaint_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_attachments_complaint_id'), ['complaint_id'], unique=False)

    op.create_table('complaint_entities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('normalized', sa.String(length=512), nullable=True),
    sa.Column('span_start', sa.Integer(), nullable=True),
    sa.Column('span_end', sa.Integer(), nullable=True),
    sa.Column('extracted_by', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("extracted_by IN ('PYTHON', 'GENAI')", name=op.f('ck_complaint_entities_extracted_by_valid')),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_complaint_entities_complaint_id_complaints'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaint_entities'))
    )
    with op.batch_alter_table('complaint_entities', schema=None) as batch_op:
        batch_op.create_index('ix_entities_complaint_type', ['complaint_id', 'entity_type'], unique=False)

    op.create_table('complaint_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('related_id', sa.Uuid(), nullable=False),
    sa.Column('link_type', sa.String(length=24), nullable=False),
    sa.Column('similarity', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('detected_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("link_type IN ('EXACT_DUPLICATE', 'NEAR_DUPLICATE', 'REPEAT', 'RELATED', 'FOLLOW_UP')", name=op.f('ck_complaint_links_link_type_valid')),
    sa.CheckConstraint('complaint_id <> related_id', name=op.f('ck_complaint_links_no_self_link')),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_complaint_links_complaint_id_complaints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_id'], ['complaints.id'], name=op.f('fk_complaint_links_related_id_complaints'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaint_links')),
    sa.UniqueConstraint('complaint_id', 'related_id', 'link_type', name='uq_link_pair_type')
    )
    with op.batch_alter_table('complaint_links', schema=None) as batch_op:
        batch_op.create_index('ix_links_complaint', ['complaint_id'], unique=False)

    op.create_table('complaint_status_history',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_complaint_status_history_changed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_complaint_status_history_complaint_id_complaints'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaint_status_history'))
    )
    with op.batch_alter_table('complaint_status_history', schema=None) as batch_op:
        batch_op.create_index('ix_statushist_complaint', ['complaint_id', 'created_at'], unique=False)

    op.create_table('complaint_validation_issues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=True),
    sa.Column('submitted_ref', sa.String(length=255), nullable=True),
    sa.Column('submitted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('issue_code', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("issue_code IN ('EMPTY_COMPLAINT', 'TOO_SHORT', 'TOO_LONG', 'DUPLICATE_COMPLAINT', 'INVALID_REFERENCE_ID', 'MISSING_MANDATORY_FIELD', 'UNSUPPORTED_ATTACHMENT', 'SUSPECTED_INJECTION', 'UNSUPPORTED_FILE_TYPE', 'FILE_TOO_LARGE', 'EMPTY_FILE', 'DUPLICATE_DOCUMENT', 'MISSING_DOCUMENT_ID', 'MISSING_VERSION', 'MISSING_EFFECTIVE_DATE', 'EXPIRED_DOCUMENT', 'MISSING_CATEGORY', 'NO_TEXT_LAYER', 'PARSE_FAILED', 'METADATA_INCOMPLETE')", name=op.f('ck_complaint_validation_issues_issue_code_valid')),
    sa.CheckConstraint("outcome IN ('REJECTED', 'ACCEPTED_WITH_WARNING', 'ROUTED_TO_REVIEW')", name=op.f('ck_complaint_validation_issues_outcome_valid')),
    sa.CheckConstraint("severity IN ('CRITICAL', 'HIGH', 'MEDIUM', 'INFORMATIONAL')", name=op.f('ck_complaint_validation_issues_severity_valid')),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_complaint_validation_issues_complaint_id_complaints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], name=op.f('fk_complaint_validation_issues_submitted_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaint_validation_issues'))
    )
    with op.batch_alter_table('complaint_validation_issues', schema=None) as batch_op:
        batch_op.create_index('ix_cvi_code', ['issue_code', 'created_at'], unique=False)
        batch_op.create_index('ix_cvi_complaint', ['complaint_id'], unique=False)

    op.create_table('document_sections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('section_ref', sa.String(length=64), nullable=False),
    sa.Column('heading', sa.String(length=255), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('paragraph_index', sa.Integer(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_document_sections_document_version_id_document_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_sections')),
    sa.UniqueConstraint('document_version_id', 'section_ref', name='uq_section_docver_ref')
    )
    with op.batch_alter_table('document_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_sections_document_version_id'), ['document_version_id'], unique=False)

    op.create_table('document_validation_issues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=True),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('issue_code', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("issue_code IN ('EMPTY_COMPLAINT', 'TOO_SHORT', 'TOO_LONG', 'DUPLICATE_COMPLAINT', 'INVALID_REFERENCE_ID', 'MISSING_MANDATORY_FIELD', 'UNSUPPORTED_ATTACHMENT', 'SUSPECTED_INJECTION', 'UNSUPPORTED_FILE_TYPE', 'FILE_TOO_LARGE', 'EMPTY_FILE', 'DUPLICATE_DOCUMENT', 'MISSING_DOCUMENT_ID', 'MISSING_VERSION', 'MISSING_EFFECTIVE_DATE', 'EXPIRED_DOCUMENT', 'MISSING_CATEGORY', 'NO_TEXT_LAYER', 'PARSE_FAILED', 'METADATA_INCOMPLETE')", name=op.f('ck_document_validation_issues_issue_code_valid')),
    sa.CheckConstraint("outcome IN ('REJECTED', 'ACCEPTED_WITH_WARNING', 'ROUTED_TO_REVIEW')", name=op.f('ck_document_validation_issues_outcome_valid')),
    sa.CheckConstraint("severity IN ('CRITICAL', 'HIGH', 'MEDIUM', 'INFORMATIONAL')", name=op.f('ck_document_validation_issues_severity_valid')),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_document_validation_issues_document_version_id_document_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_document_validation_issues_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_validation_issues'))
    )
    with op.batch_alter_table('document_validation_issues', schema=None) as batch_op:
        batch_op.create_index('ix_dvi_code', ['issue_code', 'created_at'], unique=False)
        batch_op.create_index('ix_dvi_docver', ['document_version_id'], unique=False)

    op.create_table('eligibility_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('eligibility_type', sa.String(length=24), nullable=False),
    sa.Column('genai_outcome', sa.String(length=24), nullable=True),
    sa.Column('python_outcome', sa.String(length=24), nullable=False),
    sa.Column('final_outcome', sa.String(length=24), nullable=False),
    sa.Column('overridden', sa.Boolean(), nullable=False),
    sa.Column('conditions_evaluated', JSONType, nullable=False),
    sa.Column('rule_ref', sa.String(length=64), nullable=True),
    sa.Column('policy_ref', sa.String(length=64), nullable=True),
    sa.Column('section_ref', sa.String(length=64), nullable=True),
    sa.Column('max_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requires_human_approval', sa.Boolean(), nullable=False),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("eligibility_type IN ('REFUND', 'REPLACEMENT', 'COMPENSATION', 'REPAIR', 'POLICY_EXCEPTION')", name=op.f('ck_eligibility_decisions_eligibility_type_valid')),
    sa.CheckConstraint("final_outcome IN ('ELIGIBLE', 'NOT_ELIGIBLE', 'CONDITIONAL', 'REQUIRES_VERIFICATION', 'NOT_APPLICABLE')", name=op.f('ck_eligibility_decisions_final_outcome_valid')),
    sa.CheckConstraint("genai_outcome IN ('ELIGIBLE', 'NOT_ELIGIBLE', 'CONDITIONAL', 'REQUIRES_VERIFICATION', 'NOT_APPLICABLE')", name=op.f('ck_eligibility_decisions_genai_outcome_valid')),
    sa.CheckConstraint("python_outcome IN ('ELIGIBLE', 'NOT_ELIGIBLE', 'CONDITIONAL', 'REQUIRES_VERIFICATION', 'NOT_APPLICABLE')", name=op.f('ck_eligibility_decisions_python_outcome_valid')),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_eligibility_decisions_complaint_id_complaints'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eligibility_decisions')),
    sa.UniqueConstraint('complaint_id', 'eligibility_type', name='uq_elig_complaint_type')
    )
    with op.batch_alter_table('eligibility_decisions', schema=None) as batch_op:
        batch_op.create_index('ix_elig_type_outcome', ['eligibility_type', 'final_outcome'], unique=False)

    op.create_table('escalations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('escalation_code', sa.String(length=64), nullable=False),
    sa.Column('triggered_by', sa.String(length=16), nullable=False),
    sa.Column('rule_ref', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('to_department_id', sa.Uuid(), nullable=True),
    sa.Column('acknowledged_by', sa.Uuid(), nullable=True),
    sa.Column('acknowledged_at', TZDateTime(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("triggered_by IN ('PYTHON_RULE', 'GENAI', 'REVIEWER', 'SLA')", name=op.f('ck_escalations_triggered_by_valid')),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], name=op.f('fk_escalations_acknowledged_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_escalations_complaint_id_complaints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['escalation_code'], ['escalation_levels.code'], name=op.f('fk_escalations_escalation_code_escalation_levels')),
    sa.ForeignKeyConstraint(['to_department_id'], ['departments.id'], name=op.f('fk_escalations_to_department_id_departments'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_escalations'))
    )
    with op.batch_alter_table('escalations', schema=None) as batch_op:
        batch_op.create_index('ix_escalations_complaint', ['complaint_id', 'created_at'], unique=False)

    op.create_table('follow_ups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('follow_up_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('due_at', TZDateTime(), nullable=True),
    sa.Column('completed_at', TZDateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_follow_ups_complaint_id_complaints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_follow_ups_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_follow_ups'))
    )
    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follow_ups_complaint_id'), ['complaint_id'], unique=False)
        batch_op.create_index('ix_followups_due', ['due_at', 'completed_at'], unique=False)

    op.create_table('genai_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('pipeline', sa.String(length=32), nullable=False),
    sa.Column('prompt_name', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('request_payload', JSONType, nullable=True),
    sa.Column('response_raw', sa.Text(), nullable=True),
    sa.Column('parsed_json', JSONType, nullable=True),
    sa.Column('schema_errors', JSONType, nullable=True),
    sa.Column('retrieved_chunk_ids', JSONType, nullable=False),
    sa.Column('knowledge_base_version', sa.String(length=64), nullable=True),
    sa.Column('policy_snapshot', JSONType, nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("pipeline IN ('INTELLIGENCE', 'RESPONSE', 'CLARIFICATION', 'ESCALATION_NOTE')", name=op.f('ck_genai_runs_pipeline_valid')),
    sa.CheckConstraint("status IN ('PENDING', 'SUCCESS', 'SCHEMA_INVALID', 'REPAIRED', 'API_ERROR', 'TIMEOUT', 'RATE_LIMITED', 'CACHED', 'FAILED')", name=op.f('ck_genai_runs_status_valid')),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_genai_runs_complaint_id_complaints'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genai_runs'))
    )
    with op.batch_alter_table('genai_runs', schema=None) as batch_op:
        batch_op.create_index('ix_genai_complaint_created', ['complaint_id', 'created_at'], unique=False)
        batch_op.create_index('ix_genai_status_created', ['status', 'created_at'], unique=False)

    op.create_table('impact_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('new_document_version_id', sa.Uuid(), nullable=False),
    sa.Column('old_document_version_id', sa.Uuid(), nullable=True),
    sa.Column('changed_sections', JSONType, nullable=False),
    sa.Column('affected_rule_count', sa.Integer(), nullable=False),
    sa.Column('affected_complaint_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_impact_analyses_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['new_document_version_id'], ['document_versions.id'], name=op.f('fk_impact_analyses_new_document_version_id_document_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['old_document_version_id'], ['document_versions.id'], name=op.f('fk_impact_analyses_old_document_version_id_document_versions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_impact_analyses'))
    )
    op.create_table('injection_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=True),
    sa.Column('document_version_id', sa.Uuid(), nullable=True),
    sa.Column('pattern_label', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('matched_spans', JSONType, nullable=False),
    sa.Column('action_taken', sa.String(length=24), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("action_taken IN ('FLAGGED', 'NEUTRALIZED', 'BLOCKED', 'REVIEW_ROUTED')", name=op.f('ck_injection_events_action_taken_valid')),
    sa.CheckConstraint("severity IN ('CRITICAL', 'HIGH', 'MEDIUM', 'INFORMATIONAL')", name=op.f('ck_injection_events_severity_valid')),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_injection_events_complaint_id_complaints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_injection_events_document_version_id_document_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_injection_events'))
    )
    with op.batch_alter_table('injection_events', schema=None) as batch_op:
        batch_op.create_index('ix_injection_complaint', ['complaint_id'], unique=False)
        batch_op.create_index('ix_injection_created', ['created_at'], unique=False)

    op.create_table('review_queue',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('reasons', JSONType, nullable=False),
    sa.Column('priority_code', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('closed_at', TZDateTime(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('OPEN', 'IN_REVIEW', 'RESOLVED', 'DISMISSED')", name=op.f('ck_review_queue_status_valid')),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_review_queue_assigned_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_review_queue_complaint_id_complaints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['priority_code'], ['priority_levels.code'], name=op.f('fk_review_queue_priority_code_priority_levels'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_queue'))
    )
    with op.batch_alter_table('review_queue', schema=None) as batch_op:
        batch_op.create_index('ix_review_assigned', ['assigned_to', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_queue_complaint_id'), ['complaint_id'], unique=False)
        batch_op.create_index('ix_review_status_opened', ['status', 'created_at'], unique=False)

    op.create_table('sla_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('due_at', TZDateTime(), nullable=False),
    sa.Column('met_at', TZDateTime(), nullable=True),
    sa.Column('breached', sa.Boolean(), nullable=False),
    sa.Column('at_risk', sa.Boolean(), nullable=False),
    sa.Column('sla_policy_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_sla_events_complaint_id_complaints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sla_policy_id'], ['sla_policies.id'], name=op.f('fk_sla_events_sla_policy_id_sla_policies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sla_events'))
    )
    with op.batch_alter_table('sla_events', schema=None) as batch_op:
        batch_op.create_index('ix_sla_complaint', ['complaint_id'], unique=False)
        batch_op.create_index('ix_sla_open_due', ['due_at', 'met_at'], unique=False)

    op.create_table('validation_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('ruleset_version', sa.String(length=64), nullable=False),
    sa.Column('knowledge_base_version', sa.String(length=64), nullable=True),
    sa.Column('signals', JSONType, nullable=False),
    sa.Column('derived_category_id', sa.Uuid(), nullable=True),
    sa.Column('derived_subcategory_id', sa.Uuid(), nullable=True),
    sa.Column('derived_department_id', sa.Uuid(), nullable=True),
    sa.Column('derived_support_department_id', sa.Uuid(), nullable=True),
    sa.Column('derived_urgency', sa.String(length=16), nullable=True),
    sa.Column('derived_priority_code', sa.String(length=8), nullable=True),
    sa.Column('derived_escalation_code', sa.String(length=64), nullable=True),
    sa.Column('escalation_floor_code', sa.String(length=64), nullable=True),
    sa.Column('required_actions', JSONType, nullable=False),
    sa.Column('prohibited_actions', JSONType, nullable=False),
    sa.Column('policy_refs', JSONType, nullable=False),
    sa.Column('follow_up_required', sa.Boolean(), nullable=False),
    sa.Column('reason_codes', JSONType, nullable=False),
    sa.Column('unmatched', sa.Boolean(), nullable=False),
    sa.Column('conflict_detected', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("derived_urgency IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name=op.f('ck_validation_runs_derived_urgency_valid')),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_validation_runs_complaint_id_complaints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['derived_category_id'], ['categories.id'], name=op.f('fk_validation_runs_derived_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['derived_department_id'], ['departments.id'], name=op.f('fk_validation_runs_derived_department_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['derived_escalation_code'], ['escalation_levels.code'], name=op.f('fk_validation_runs_derived_escalation_code_escalation_levels'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['derived_priority_code'], ['priority_levels.code'], name=op.f('fk_validation_runs_derived_priority_code_priority_levels'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['derived_subcategory_id'], ['subcategories.id'], name=op.f('fk_validation_runs_derived_subcategory_id_subcategories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['derived_support_department_id'], ['departments.id'], name=op.f('fk_validation_runs_derived_support_department_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['escalation_floor_code'], ['escalation_levels.code'], name=op.f('fk_validation_runs_escalation_floor_code_escalation_levels'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_runs'))
    )
    with op.batch_alter_table('validation_runs', schema=None) as batch_op:
        batch_op.create_index('ix_valrun_complaint_created', ['complaint_id', 'created_at'], unique=False)

    op.create_table('chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.Column('chunk_key', sa.String(length=255), nullable=False),
    sa.Column('doc_ref', sa.String(length=64), nullable=False),
    sa.Column('doc_version', sa.String(length=32), nullable=False),
    sa.Column('section_ref', sa.String(length=64), nullable=True),
    sa.Column('heading', sa.String(length=255), nullable=True),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('paragraph_index', sa.Integer(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding', Vector(768), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_chunks_document_version_id_document_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['document_sections.id'], name=op.f('fk_chunks_section_id_document_sections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks')),
    sa.UniqueConstraint('document_version_id', 'chunk_key', name='uq_chunk_docver_key')
    )
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chunks_chunk_key'), ['chunk_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunks_doc_ref'), ['doc_ref'], unique=False)
        batch_op.create_index('ix_chunks_docver_ordinal', ['document_version_id', 'ordinal'], unique=False)

    op.create_table('clarification_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('genai_run_id', sa.Uuid(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('missing_field', sa.String(length=64), nullable=True),
    sa.Column('required_for', sa.String(length=255), nullable=True),
    sa.Column('asked_at', TZDateTime(), nullable=True),
    sa.Column('answered_at', TZDateTime(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_clarification_questions_complaint_id_complaints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genai_run_id'], ['genai_runs.id'], name=op.f('fk_clarification_questions_genai_run_id_genai_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clarification_questions'))
    )
    with op.batch_alter_table('clarification_questions', schema=None) as batch_op:
        batch_op.create_index('ix_clarq_complaint', ['complaint_id', 'ordinal'], unique=False)

    op.create_table('comparisons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('genai_run_id', sa.Uuid(), nullable=True),
    sa.Column('validation_run_id', sa.Uuid(), nullable=True),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('genai_value', sa.String(length=512), nullable=True),
    sa.Column('python_value', sa.String(length=512), nullable=True),
    sa.Column('final_value', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('winner', sa.String(length=16), nullable=True),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("severity IN ('CRITICAL', 'HIGH', 'MEDIUM', 'INFORMATIONAL')", name=op.f('ck_comparisons_severity_valid')),
    sa.CheckConstraint("status IN ('MATCH', 'MISMATCH', 'GENAI_MISSING', 'PYTHON_MISSING', 'UNSUPPORTED', 'CORRECTED')", name=op.f('ck_comparisons_status_valid')),
    sa.CheckConstraint("winner IN ('GENAI', 'PYTHON', 'AGREED', 'NONE')", name=op.f('ck_comparisons_winner_valid')),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_comparisons_complaint_id_complaints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genai_run_id'], ['genai_runs.id'], name=op.f('fk_comparisons_genai_run_id_genai_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_runs.id'], name=op.f('fk_comparisons_validation_run_id_validation_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comparisons'))
    )
    with op.batch_alter_table('comparisons', schema=None) as batch_op:
        batch_op.create_index('ix_comparisons_complaint', ['complaint_id'], unique=False)
        batch_op.create_index('ix_comparisons_field', ['field'], unique=False)
        batch_op.create_index('ix_comparisons_status_severity', ['status', 'severity'], unique=False)

    op.create_table('complaint_policy_refs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('genai_run_id', sa.Uuid(), nullable=True),
    sa.Column('validation_run_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('doc_ref', sa.String(length=64), nullable=False),
    sa.Column('section_ref', sa.String(length=64), nullable=True),
    sa.Column('doc_version', sa.String(length=32), nullable=True),
    sa.Column('chunk_key', sa.String(length=255), nullable=True),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('paragraph_index', sa.Integer(), nullable=True),
    sa.Column('document_version_id', sa.Uuid(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('was_active', sa.Boolean(), nullable=False),
    sa.Column('applicability', sa.String(length=32), nullable=False),
    sa.Column('precedence_tier', sa.String(length=64), nullable=True),
    sa.Column('conflict_with_ref', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("applicability IN ('APPLICABLE', 'CONDITIONALLY_APPLICABLE', 'NOT_APPLICABLE', 'OUTDATED')", name=op.f('ck_complaint_policy_refs_applicability_valid')),
    sa.CheckConstraint("source IN ('GENAI', 'PYTHON', 'RETRIEVAL')", name=op.f('ck_complaint_policy_refs_source_valid')),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_complaint_policy_refs_complaint_id_complaints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_complaint_policy_refs_document_version_id_document_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['genai_run_id'], ['genai_runs.id'], name=op.f('fk_complaint_policy_refs_genai_run_id_genai_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_runs.id'], name=op.f('fk_complaint_policy_refs_validation_run_id_validation_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaint_policy_refs'))
    )
    with op.batch_alter_table('complaint_policy_refs', schema=None) as batch_op:
        batch_op.create_index('ix_cpr_applicability', ['applicability'], unique=False)
        batch_op.create_index('ix_cpr_complaint', ['complaint_id'], unique=False)
        batch_op.create_index('ix_cpr_docref', ['doc_ref', 'section_ref'], unique=False)

    op.create_table('impact_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('impact_analysis_id', sa.Uuid(), nullable=False),
    sa.Column('item_type', sa.String(length=16), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('item_ref', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('regenerated', sa.Boolean(), nullable=False),
    sa.Column('regenerated_at', TZDateTime(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['impact_analysis_id'], ['impact_analyses.id'], name=op.f('fk_impact_items_impact_analysis_id_impact_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_impact_items'))
    )
    with op.batch_alter_table('impact_items', schema=None) as batch_op:
        batch_op.create_index('ix_impactitems_analysis', ['impact_analysis_id', 'item_type'], unique=False)

    op.create_table('resolution_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('genai_run_id', sa.Uuid(), nullable=True),
    sa.Column('validation_run_id', sa.Uuid(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('action_code', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rule_ref', sa.String(length=64), nullable=True),
    sa.Column('policy_ref', sa.String(length=64), nullable=True),
    sa.Column('section_ref', sa.String(length=64), nullable=True),
    sa.Column('chunk_key', sa.String(length=255), nullable=True),
    sa.Column('support_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("source IN ('GENAI', 'RULE_REQUIRED')", name=op.f('ck_resolution_steps_source_valid')),
    sa.CheckConstraint("status IN ('SUPPORTED', 'REQUIRED_MET', 'MISSING', 'UNSUPPORTED', 'PROHIBITED', 'DUPLICATE')", name=op.f('ck_resolution_steps_status_valid')),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_resolution_steps_complaint_id_complaints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genai_run_id'], ['genai_runs.id'], name=op.f('fk_resolution_steps_genai_run_id_genai_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_runs.id'], name=op.f('fk_resolution_steps_validation_run_id_validation_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resolution_steps'))
    )
    with op.batch_alter_table('resolution_steps', schema=None) as batch_op:
        batch_op.create_index('ix_resstep_complaint_order', ['complaint_id', 'ordinal'], unique=False)
        batch_op.create_index('ix_resstep_status', ['status'], unique=False)

    op.create_table('responses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('genai_run_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tone', sa.String(length=24), nullable=False),
    sa.Column('draft_text', sa.Text(), nullable=False),
    sa.Column('final_text', sa.Text(), nullable=True),
    sa.Column('citations', JSONType, nullable=False),
    sa.Column('guard_status', sa.String(length=24), nullable=False),
    sa.Column('regeneration_count', sa.Integer(), nullable=False),
    sa.Column('edited_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', TZDateTime(), nullable=True),
    sa.Column('sent_at', TZDateTime(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("guard_status IN ('PENDING', 'CLEAN', 'FLAGGED', 'BLOCKED', 'REGENERATED')", name=op.f('ck_responses_guard_status_valid')),
    sa.CheckConstraint("tone IN ('PROFESSIONAL', 'EMPATHETIC', 'CONCISE', 'FORMAL')", name=op.f('ck_responses_tone_valid')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_responses_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_responses_complaint_id_complaints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], name=op.f('fk_responses_edited_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['genai_run_id'], ['genai_runs.id'], name=op.f('fk_responses_genai_run_id_genai_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_responses')),
    sa.UniqueConstraint('complaint_id', 'version', name='uq_response_complaint_version')
    )
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.create_index('ix_responses_complaint', ['complaint_id', 'version'], unique=False)

    op.create_table('review_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('review_queue_id', sa.Uuid(), nullable=True),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('is_override', sa.Boolean(), nullable=False),
    sa.Column('original_value', JSONType, nullable=True),
    sa.Column('new_value', JSONType, nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("action IN ('APPROVE', 'REJECT', 'MODIFY', 'RECLASSIFY', 'REASSIGN', 'ESCALATE', 'REGENERATE', 'COMMENT', 'OVERRIDE')", name=op.f('ck_review_actions_action_valid')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_review_actions_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_review_actions_complaint_id_complaints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_queue_id'], ['review_queue.id'], name=op.f('fk_review_actions_review_queue_id_review_queue'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_actions'))
    )
    with op.batch_alter_table('review_actions', schema=None) as batch_op:
        batch_op.create_index('ix_reviewactions_complaint', ['complaint_id', 'created_at'], unique=False)

    op.create_table('rule_hits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('validation_run_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('rule_ref', sa.String(length=64), nullable=False),
    sa.Column('precedence', sa.Integer(), nullable=False),
    sa.Column('matched_signals', JSONType, nullable=False),
    sa.Column('matched_spans', JSONType, nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], name=op.f('fk_rule_hits_rule_id_rules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_runs.id'], name=op.f('fk_rule_hits_validation_run_id_validation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_hits'))
    )
    with op.batch_alter_table('rule_hits', schema=None) as batch_op:
        batch_op.create_index('ix_rulehits_rule', ['rule_id'], unique=False)
        batch_op.create_index('ix_rulehits_run', ['validation_run_id'], unique=False)

    op.create_table('verification_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('complaint_id', sa.Uuid(), nullable=False),
    sa.Column('genai_run_id', sa.Uuid(), nullable=True),
    sa.Column('validation_run_id', sa.Uuid(), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('critical_mismatches', sa.Integer(), nullable=False),
    sa.Column('high_mismatches', sa.Integer(), nullable=False),
    sa.Column('total_fields', sa.Integer(), nullable=False),
    sa.Column('matched_fields', sa.Integer(), nullable=False),
    sa.Column('agreement_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('traceability_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('compliance_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('review_reasons', JSONType, nullable=False),
    sa.Column('reconciled', JSONType, nullable=False),
    sa.Column('genai_available', sa.Boolean(), nullable=False),
    sa.Column('decided_at', TZDateTime(), nullable=True),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("outcome IN ('VERIFIED', 'VERIFIED_WITH_WARNING', 'CORRECTED_BY_RULES', 'MANUAL_REVIEW_REQUIRED', 'BLOCKED', 'INCOMPLETE')", name=op.f('ck_verification_decisions_outcome_valid')),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], name=op.f('fk_verification_decisions_complaint_id_complaints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genai_run_id'], ['genai_runs.id'], name=op.f('fk_verification_decisions_genai_run_id_genai_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_runs.id'], name=op.f('fk_verification_decisions_validation_run_id_validation_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_decisions'))
    )
    with op.batch_alter_table('verification_decisions', schema=None) as batch_op:
        batch_op.create_index('ix_verdict_complaint', ['complaint_id', 'created_at'], unique=False)
        batch_op.create_index('ix_verdict_outcome', ['outcome'], unique=False)

    op.create_table('response_flags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('response_id', sa.Uuid(), nullable=False),
    sa.Column('flag_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('matched_text', sa.String(length=1024), nullable=True),
    sa.Column('span_start', sa.Integer(), nullable=True),
    sa.Column('span_end', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('blocking_rule_ref', sa.String(length=64), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', TZDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("flag_type IN ('UNSUPPORTED_PROMISE', 'HALLUCINATION', 'INVALID_CITATION', 'OUTDATED_POLICY', 'PROHIBITED_ACTION', 'MISSING_ACTION')", name=op.f('ck_response_flags_flag_type_valid')),
    sa.CheckConstraint("severity IN ('CRITICAL', 'HIGH', 'MEDIUM', 'INFORMATIONAL')", name=op.f('ck_response_flags_severity_valid')),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], name=op.f('fk_response_flags_response_id_responses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_response_flags'))
    )
    with op.batch_alter_table('response_flags', schema=None) as batch_op:
        batch_op.create_index('ix_respflags_response', ['response_id'], unique=False)
        batch_op.create_index('ix_respflags_type', ['flag_type'], unique=False)

    # ### end Alembic commands ###

    # PostgreSQL-only search / similarity indexes, created after the tables
    # they cover. No portable SQLAlchemy equivalent exists for GIN trigram,
    # tsvector expression or ivfflat indexes.

    if _is_postgres():
        for statement in POSTGRES_INDEXES:
            op.execute(statement)


def downgrade() -> None:
    if _is_postgres():
        for statement in POSTGRES_DROP_INDEXES:
            op.execute(statement)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response_flags', schema=None) as batch_op:
        batch_op.drop_index('ix_respflags_type')
        batch_op.drop_index('ix_respflags_response')

    op.drop_table('response_flags')
    with op.batch_alter_table('verification_decisions', schema=None) as batch_op:
        batch_op.drop_index('ix_verdict_outcome')
        batch_op.drop_index('ix_verdict_complaint')

    op.drop_table('verification_decisions')
    with op.batch_alter_table('rule_hits', schema=None) as batch_op:
        batch_op.drop_index('ix_rulehits_run')
        batch_op.drop_index('ix_rulehits_rule')

    op.drop_table('rule_hits')
    with op.batch_alter_table('review_actions', schema=None) as batch_op:
        batch_op.drop_index('ix_reviewactions_complaint')

    op.drop_table('review_actions')
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_index('ix_responses_complaint')

    op.drop_table('responses')
    with op.batch_alter_table('resolution_steps', schema=None) as batch_op:
        batch_op.drop_index('ix_resstep_status')
        batch_op.drop_index('ix_resstep_complaint_order')

    op.drop_table('resolution_steps')
    with op.batch_alter_table('impact_items', schema=None) as batch_op:
        batch_op.drop_index('ix_impactitems_analysis')

    op.drop_table('impact_items')
    with op.batch_alter_table('complaint_policy_refs', schema=None) as batch_op:
        batch_op.drop_index('ix_cpr_docref')
        batch_op.drop_index('ix_cpr_complaint')
        batch_op.drop_index('ix_cpr_applicability')

    op.drop_table('complaint_policy_refs')
    with op.batch_alter_table('comparisons', schema=None) as batch_op:
        batch_op.drop_index('ix_comparisons_status_severity')
        batch_op.drop_index('ix_comparisons_field')
        batch_op.drop_index('ix_comparisons_complaint')

    op.drop_table('comparisons')
    with op.batch_alter_table('clarification_questions', schema=None) as batch_op:
        batch_op.drop_index('ix_clarq_complaint')

    op.drop_table('clarification_questions')
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.drop_index('ix_chunks_docver_ordinal')
        batch_op.drop_index(batch_op.f('ix_chunks_doc_ref'))
        batch_op.drop_index(batch_op.f('ix_chunks_chunk_key'))

    op.drop_table('chunks')
    with op.batch_alter_table('validation_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_valrun_complaint_created')

    op.drop_table('validation_runs')
    with op.batch_alter_table('sla_events', schema=None) as batch_op:
        batch_op.drop_index('ix_sla_open_due')
        batch_op.drop_index('ix_sla_complaint')

    op.drop_table('sla_events')
    with op.batch_alter_table('review_queue', schema=None) as batch_op:
        batch_op.drop_index('ix_review_status_opened')
        batch_op.drop_index(batch_op.f('ix_review_queue_complaint_id'))
        batch_op.drop_index('ix_review_assigned')

    op.drop_table('review_queue')
    with op.batch_alter_table('injection_events', schema=None) as batch_op:
        batch_op.drop_index('ix_injection_created')
        batch_op.drop_index('ix_injection_complaint')

    op.drop_table('injection_events')
    op.drop_table('impact_analyses')
    with op.batch_alter_table('genai_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_genai_status_created')
        batch_op.drop_index('ix_genai_complaint_created')

    op.drop_table('genai_runs')
    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.drop_index('ix_followups_due')
        batch_op.drop_index(batch_op.f('ix_follow_ups_complaint_id'))

    op.drop_table('follow_ups')
    with op.batch_alter_table('escalations', schema=None) as batch_op:
        batch_op.drop_index('ix_escalations_complaint')

    op.drop_table('escalations')
    with op.batch_alter_table('eligibility_decisions', schema=None) as batch_op:
        batch_op.drop_index('ix_elig_type_outcome')

    op.drop_table('eligibility_decisions')
    with op.batch_alter_table('document_validation_issues', schema=None) as batch_op:
        batch_op.drop_index('ix_dvi_docver')
        batch_op.drop_index('ix_dvi_code')

    op.drop_table('document_validation_issues')
    with op.batch_alter_table('document_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_sections_document_version_id'))

    op.drop_table('document_sections')
    with op.batch_alter_table('complaint_validation_issues', schema=None) as batch_op:
        batch_op.drop_index('ix_cvi_complaint')
        batch_op.drop_index('ix_cvi_code')

    op.drop_table('complaint_validation_issues')
    with op.batch_alter_table('complaint_status_history', schema=None) as batch_op:
        batch_op.drop_index('ix_statushist_complaint')

    op.drop_table('complaint_status_history')
    with op.batch_alter_table('complaint_links', schema=None) as batch_op:
        batch_op.drop_index('ix_links_complaint')

    op.drop_table('complaint_links')
    with op.batch_alter_table('complaint_entities', schema=None) as batch_op:
        batch_op.drop_index('ix_entities_complaint_type')

    op.drop_table('complaint_entities')
    with op.batch_alter_table('complaint_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaint_attachments_complaint_id'))

    op.drop_table('complaint_attachments')
    with op.batch_alter_table('benchmark_results', schema=None) as batch_op:
        batch_op.drop_index('ix_benchresults_run_field')
        batch_op.drop_index('ix_benchresults_complaint')

    op.drop_table('benchmark_results')
    with op.batch_alter_table('agent_guidance', schema=None) as batch_op:
        batch_op.drop_index('ix_guidance_complaint')

    op.drop_table('agent_guidance')
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_index('ix_rules_mandatory')
        batch_op.drop_index('ix_rules_active_precedence')

    op.drop_table('rules')
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.drop_index('ux_docver_one_active', postgresql_where=sa.text("status = 'ACTIVE'"), sqlite_where=sa.text("status = 'ACTIVE'"))
        batch_op.drop_index('ix_docver_ref_version')
        batch_op.drop_index(batch_op.f('ix_document_versions_doc_ref'))

    op.drop_table('document_versions')
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaints_verification_outcome'))
        batch_op.drop_index(batch_op.f('ix_complaints_status'))
        batch_op.drop_index(batch_op.f('ix_complaints_order_ref'))
        batch_op.drop_index('ix_comp_status_created')
        batch_op.drop_index('ix_comp_queue')
        batch_op.drop_index('ix_comp_dataset')
        batch_op.drop_index('ix_comp_customer')
        batch_op.drop_index('ix_comp_assigned')

    op.drop_table('complaints')
    op.drop_table('benchmark_runs')
    op.drop_table('subcategories')
    op.drop_table('sla_policies')
    op.drop_table('report_exports')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_type')
        batch_op.drop_index('ix_jobs_status_created')

    op.drop_table('jobs')
    op.drop_table('documents')
    op.drop_table('customers')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_entity')
        batch_op.drop_index('ix_audit_actor')

    op.drop_table('audit_log')
    op.drop_table('app_config')
    op.drop_table('users')
    op.drop_table('categories')
    with op.batch_alter_table('trend_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_trend_metric_period')

    op.drop_table('trend_snapshots')
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.drop_index('ux_prompt_one_active', postgresql_where=sa.text('is_active = true'), sqlite_where=sa.text('is_active = 1'))

    op.drop_table('prompt_versions')
    op.drop_table('promise_patterns')
    op.drop_table('priority_levels')
    op.drop_table('llm_cache')
    with op.batch_alter_table('lexicon_terms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lexicon_terms_signal_key'))

    op.drop_table('lexicon_terms')
    op.drop_table('injection_patterns')
    op.drop_table('escalation_levels')
    op.drop_table('departments')
    # ### end Alembic commands ###
