// SupportNova API client.
//
// Every one of the backend's 84 operations, typed from the OpenAPI document
// (lib/api-types.d.ts, generated by `openapi-typescript`). If the backend
// changes shape, `next build` fails here rather than a page failing at runtime.
//
// Credentials: the access token lives in memory only. The refresh token never
// reaches this code -- it is an httpOnly cookie handled by the same-origin
// session proxy under app/api/session. There is no Supabase client, no
// service-role key and nothing in localStorage.

import type { components } from '@/lib/api-types'

export type S = components['schemas']

const API_BASE = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:8000'

/* ------------------------------------------------------------------ tokens */

let accessToken: string | null = null
export const setAccessToken = (t: string | null) => { accessToken = t }
export const getAccessToken = () => accessToken

/* ------------------------------------------------------------------ errors */

export class ApiError extends Error {
  constructor(public status: number, message: string, public detail?: unknown) {
    super(message)
    this.name = 'ApiError'
  }
}

/**
 * A readable sentence out of any error body this backend produces.
 *
 * It does not use FastAPI's default `{detail: ...}`. Every handled error
 * comes back as `{error: {code, message, details, request_id}}`, and a parser
 * that only knew `detail` silently replaced the server's actual explanation
 * with a generic fallback — which defeats the whole point of the API
 * bothering to explain itself.
 */
function describe(status: number, body: unknown): string {
  if (body && typeof body === 'object' && 'error' in body) {
    const e = (body as { error: unknown }).error
    if (e && typeof e === 'object') {
      const err = e as { message?: unknown; details?: { fields?: Array<{ field?: string; message?: string }> } }
      const fields = err.details?.fields
      if (Array.isArray(fields) && fields.length) {
        return fields.map((f) => (f.field ? `${f.field}: ${f.message}` : f.message)).join('; ')
      }
      if (typeof err.message === 'string' && err.message) return err.message
    }
  }
  if (body && typeof body === 'object' && 'detail' in body) {
    const d = (body as { detail: unknown }).detail
    if (typeof d === 'string') return d
    if (Array.isArray(d)) {
      return d
        .map((e) => {
          const loc = Array.isArray(e?.loc) ? e.loc.filter((x: unknown) => x !== 'body').join('.') : ''
          return loc ? `${loc}: ${e?.msg ?? 'invalid'}` : String(e?.msg ?? 'invalid')
        })
        .join('; ')
    }
    if (d && typeof d === 'object' && 'message' in d) return String((d as { message: unknown }).message)
  }
  if (status === 401) return 'Your session has expired. Please sign in again.'
  if (status === 403) return 'Your role does not allow that.'
  if (status === 404) return 'Not found.'
  if (status === 429) return 'Too many requests. Please wait a moment.'
  if (status >= 500) return 'The server had a problem. Please try again.'
  return `Request failed (${status}).`
}

/* ------------------------------------------------------------------ fetch */

type Opts = Omit<RequestInit, 'body'> & { body?: unknown; retried?: boolean; raw?: boolean }

let refreshing: Promise<boolean> | null = null
let sessionUser: User | null = null
export const getSessionUser = () => sessionUser

/** Rotate the session through the proxy. Concurrent callers share one attempt. */
export async function refreshSession(): Promise<boolean> {
  if (!refreshing) {
    refreshing = (async () => {
      try {
        const res = await fetch('/api/session/refresh', { method: 'POST', credentials: 'same-origin' })
        if (!res.ok) return false
        const data = (await res.json()) as SessionResponse
        accessToken = data.access_token
        sessionUser = data.user
        return true
      } catch {
        return false
      } finally {
        refreshing = null
      }
    })()
  }
  return refreshing
}

export async function apiFetch<T>(path: string, opts: Opts = {}): Promise<T> {
  const { body, retried, raw, headers: extraHeaders, ...init } = opts
  const isForm = typeof FormData !== 'undefined' && body instanceof FormData
  const headers: Record<string, string> = { ...(extraHeaders as Record<string, string>) }
  if (!isForm && body !== undefined) headers['Content-Type'] = 'application/json'
  if (accessToken) headers.Authorization = `Bearer ${accessToken}`

  let res: Response
  try {
    res = await fetch(`${API_BASE}${path}`, {
      ...init,
      headers,
      body: isForm ? (body as FormData) : body !== undefined ? JSON.stringify(body) : undefined,
    })
  } catch {
    throw new ApiError(0, 'The server could not be reached. Is the backend running?')
  }

  if (res.status === 401 && !retried) {
    if (await refreshSession()) return apiFetch<T>(path, { ...opts, retried: true })
    accessToken = null
    sessionUser = null
    if (typeof window !== 'undefined') window.dispatchEvent(new CustomEvent('auth:expired'))
  }

  if (!res.ok) {
    let parsed: unknown = null
    try { parsed = await res.json() } catch {}
    throw new ApiError(res.status, describe(res.status, parsed), parsed)
  }

  if (raw) return res as unknown as T
  if (res.status === 204) return undefined as T
  const text = await res.text()
  return (text ? JSON.parse(text) : undefined) as T
}

/** Build a query string, dropping empty values. */
export function qs(params?: object): string {
  if (!params) return ''
  const p = new URLSearchParams()
  for (const [k, v] of Object.entries(params as Record<string, unknown>)) {
    if (v === undefined || v === null || v === '') continue
    p.set(k, String(v))
  }
  const s = p.toString()
  return s ? `?${s}` : ''
}

function enc(s: string) { return encodeURIComponent(s) }

export const errorMessage = (e: unknown): string =>
  e instanceof ApiError ? e.message : e instanceof Error ? e.message : 'Something went wrong.'

/**
 * Multipart upload with real progress.
 *
 * `fetch` cannot report upload progress, and a 10 MB photo on a phone
 * connection with no feedback reads as a frozen page. XMLHttpRequest can.
 * Same auth rules as apiFetch: bearer header only, one silent refresh on 401.
 */
export function uploadWithProgress<T>(
  path: string,
  file: File,
  onProgress?: (fraction: number) => void,
  field = 'file',
  retried = false,
): Promise<T> {
  return new Promise<T>((resolve, reject) => {
    const xhr = new XMLHttpRequest()
    xhr.open('POST', `${API_BASE}${path}`)
    if (accessToken) xhr.setRequestHeader('Authorization', `Bearer ${accessToken}`)
    xhr.upload.onprogress = (e) => { if (e.lengthComputable) onProgress?.(e.loaded / e.total) }
    xhr.onerror = () => reject(new ApiError(0, 'The upload could not reach the server.'))
    xhr.onload = async () => {
      let parsed: unknown = null
      try { parsed = xhr.responseText ? JSON.parse(xhr.responseText) : null } catch {}
      if (xhr.status === 401 && !retried) {
        if (await refreshSession()) {
          try { resolve(await uploadWithProgress<T>(path, file, onProgress, field, true)) } catch (e) { reject(e) }
          return
        }
      }
      if (xhr.status >= 400) { reject(new ApiError(xhr.status, describe(xhr.status, parsed), parsed)); return }
      onProgress?.(1)
      resolve(parsed as T)
    }
    const form = new FormData()
    form.append(field, file)
    xhr.send(form)
  })
}

/* ------------------------------------------------------------------ live intake */

/** One step of a complaint's analysis, as the backend reports it. */
export interface ProgressStep {
  step: string
  state: 'active' | 'done' | 'skipped'
  label: string
  detail: string | null
  elapsed_ms: number
}

/**
 * Submit a complaint and follow its analysis step by step.
 *
 * The backend streams server-sent events: `step` as each stage starts and
 * finishes, then one `result` or `error`. EventSource cannot POST or send a
 * bearer header, so the stream is read from `fetch` directly.
 */
export async function submitWithProgress(
  data: S['ComplaintCreate'],
  analyse: boolean,
  onStep: (step: ProgressStep) => void,
  retried = false,
): Promise<S['IntakeResponse']> {
  const headers: Record<string, string> = { 'Content-Type': 'application/json', Accept: 'text/event-stream' }
  if (accessToken) headers.Authorization = `Bearer ${accessToken}`

  let res: Response
  try {
    res = await fetch(`${API_BASE}/api/complaints/stream${qs({ analyse })}`, {
      method: 'POST', headers, body: JSON.stringify(data),
    })
  } catch {
    throw new ApiError(0, 'The server could not be reached. Is the backend running?')
  }
  if (res.status === 401 && !retried) {
    if (await refreshSession()) return submitWithProgress(data, analyse, onStep, true)
    accessToken = null
    sessionUser = null
    if (typeof window !== 'undefined') window.dispatchEvent(new CustomEvent('auth:expired'))
  }
  if (!res.ok || !res.body) {
    let parsed: unknown = null
    try { parsed = await res.json() } catch {}
    throw new ApiError(res.status, describe(res.status, parsed), parsed)
  }

  const reader = res.body.pipeThrough(new TextDecoderStream()).getReader()
  let buffer = ''
  let savedRef: string | null = null
  for (;;) {
    const { value, done } = await reader.read()
    if (done) break
    buffer += value
    let cut: number
    while ((cut = buffer.indexOf('\n\n')) >= 0) {
      const block = buffer.slice(0, cut)
      buffer = buffer.slice(cut + 2)
      let kind = ''
      let payload = ''
      for (const line of block.split('\n')) {
        if (line.startsWith('event: ')) kind = line.slice(7)
        else if (line.startsWith('data: ')) payload += line.slice(6)
      }
      if (!kind || !payload) continue // a keep-alive comment
      const parsed = JSON.parse(payload)
      if (kind === 'step') {
        const step = parsed as ProgressStep
        if (step.step === 'saved' && step.state === 'done' && step.detail) savedRef = step.detail
        onStep(step)
      } else if (kind === 'result') {
        return parsed as S['IntakeResponse']
      } else if (kind === 'error') {
        const status = parsed?.error?.code === 'VALIDATION_ERROR' ? 422 : 500
        throw new ApiError(status, describe(status, parsed), parsed)
      }
    }
  }
  // The connection closed early. If the complaint was already saved it is not lost.
  throw new ApiError(
    0,
    savedRef
      ? `The connection dropped, but your complaint was saved as ${savedRef}. You can follow it from My complaints.`
      : 'The connection dropped before your complaint was saved. Please try again.',
  )
}

/* ------------------------------------------------------------------ shared types */

export type Role = 'customer' | 'agent' | 'reviewer' | 'manager' | 'admin' | 'evaluator'
export type User = Omit<S['UserOut'], 'role'> & { role: Role }
export interface SessionResponse { access_token: string; expires_in: number; user: User }
/** A correct password on an account with two-step sign-in: the code is still to come. */
export interface MfaChallenge { mfa_required: true; mfa_token: string }

export interface Page<T> { items: T[]; total: number; page?: number; page_size?: number }

export const COMPLAINT_STATUSES = [
  'NEW', 'ANALYZING', 'ANALYZED', 'VALIDATED', 'ASSIGNED', 'IN_PROGRESS', 'AWAITING_CUSTOMER',
  'ESCALATED', 'MANUAL_REVIEW', 'RESOLVED', 'CLOSED', 'REOPENED', 'FAILED',
] as const
export type ComplaintStatus = (typeof COMPLAINT_STATUSES)[number]

export const REVIEW_ACTIONS = [
  'APPROVE', 'REJECT', 'MODIFY', 'RECLASSIFY', 'REASSIGN', 'ESCALATE', 'REGENERATE', 'COMMENT', 'OVERRIDE',
] as const
export type ReviewAction = (typeof REVIEW_ACTIONS)[number]

export const URGENCIES = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] as const
export const PRIORITIES = ['P0', 'P1', 'P2', 'P3'] as const
export const VERIFICATION_OUTCOMES = [
  'VERIFIED', 'VERIFIED_WITH_WARNING', 'CORRECTED_BY_RULES', 'MANUAL_REVIEW_REQUIRED', 'BLOCKED', 'INCOMPLETE',
] as const

/* Loosely-typed analytics dictionaries the backend returns as plain objects. */
export type VolumeSeries = S['VolumeOut'] & { series?: Array<{ date: string; count: number }> }
export interface MyQueue {
  assigned: number
  by_priority: Record<string, number>
  complaints: Array<{ public_ref: string; title: string; status: string; priority?: string | null; urgency?: string | null; escalation?: string | null }>
}

/* ------------------------------------------------------------------ auth */

export const auth = {
  /** Via the session proxy so the refresh token becomes an httpOnly cookie. */
  login: async (email: string, password: string): Promise<SessionResponse | MfaChallenge> => {
    const res = await fetch('/api/session/login', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email, password }),
      credentials: 'same-origin',
    })
    if (!res.ok) {
      let parsed: unknown = null
      try { parsed = await res.json() } catch {}
      throw new ApiError(res.status, describe(res.status, parsed), parsed)
    }
    const data = (await res.json()) as SessionResponse | MfaChallenge
    if ('mfa_required' in data && data.mfa_required) return data
    const session = data as SessionResponse
    accessToken = session.access_token
    sessionUser = session.user
    return session
  },
  /** Second step of a two-step sign-in: an authenticator code or a recovery code. */
  loginMfa: async (mfa_token: string, code: string): Promise<SessionResponse> => {
    const res = await fetch('/api/session/login/mfa', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ mfa_token, code }),
      credentials: 'same-origin',
    })
    if (!res.ok) {
      let parsed: unknown = null
      try { parsed = await res.json() } catch {}
      throw new ApiError(res.status, describe(res.status, parsed), parsed)
    }
    const data = (await res.json()) as SessionResponse
    accessToken = data.access_token
    sessionUser = data.user
    return data
  },
  /** Same proxy path as login, so the refresh token lands in the cookie. */
  register: async (email: string, full_name: string, password: string): Promise<SessionResponse> => {
    const res = await fetch('/api/session/register', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email, full_name, password }),
      credentials: 'same-origin',
    })
    if (!res.ok) {
      let parsed: unknown = null
      try { parsed = await res.json() } catch {}
      throw new ApiError(res.status, describe(res.status, parsed), parsed)
    }
    const data = (await res.json()) as SessionResponse
    accessToken = data.access_token
    sessionUser = data.user
    return data
  },
  refresh: refreshSession,
  me: () => apiFetch<User>('/api/auth/me'),
  changePassword: (current_password: string, new_password: string) =>
    apiFetch<S['MessageResponse']>('/api/auth/change-password', { method: 'POST', body: { current_password, new_password } }),
  updateMe: (full_name: string) => apiFetch<User>('/api/auth/me', { method: 'PATCH', body: { full_name } }),
  security: () => apiFetch<S['SecurityOverview']>('/api/auth/security'),
  sessions: () => apiFetch<S['SessionOut'][]>('/api/auth/sessions'),
  revokeSession: (id: string) => apiFetch<S['MessageResponse']>(`/api/auth/sessions/${enc(id)}`, { method: 'DELETE' }),
  revokeOtherSessions: () => apiFetch<S['MessageResponse']>('/api/auth/sessions/revoke-others', { method: 'POST' }),
  activity: (limit = 30) => apiFetch<S['ActivityOut'][]>(`/api/auth/activity${qs({ limit })}`),
  mfaSetup: () => apiFetch<S['MfaSetupOut']>('/api/auth/mfa/setup', { method: 'POST' }),
  mfaEnable: (code: string) => apiFetch<S['RecoveryCodesOut']>('/api/auth/mfa/enable', { method: 'POST', body: { code } }),
  mfaDisable: (password: string, code: string) => apiFetch<S['MessageResponse']>('/api/auth/mfa/disable', { method: 'POST', body: { password, code } }),
  mfaRecoveryCodes: (code: string) => apiFetch<S['RecoveryCodesOut']>('/api/auth/mfa/recovery-codes', { method: 'POST', body: { code } }),
  logout: async () => {
    try {
      await fetch('/api/session/logout', {
        method: 'POST',
        headers: accessToken ? { Authorization: `Bearer ${accessToken}` } : {},
        credentials: 'same-origin',
      })
    } finally {
      accessToken = null
      sessionUser = null
    }
  },
}

/* ------------------------------------------------------------------ system */

export const system = {
  health: () => apiFetch<S['HealthResponse']>('/api/health'),
  version: () => apiFetch<S['VersionResponse']>('/api/version'),
}

/* ------------------------------------------------------------------ complaints */

export interface ComplaintFilters {
  page?: number; size?: number; status?: string; category?: string; department?: string
  urgency?: string; priority?: string; verification_outcome?: string; requires_review?: boolean
  dataset_tag?: string; customer_type?: string; sentiment?: string; escalation?: string
  date_from?: string; date_to?: string; search?: string
}

export interface ResponseDraft {
  version: number; tone?: string; draft_text?: string | null; final_text?: string | null
  guard_status?: string; citations?: unknown[]; flags?: unknown[]; approved_at?: string | null; sent_at?: string | null
}
export interface AgentItem {
  public_ref: string; title: string; status: string; assigned_to_me: boolean
  category: string | null; priority: string | null; urgency: string | null; sentiment: string | null
  team: string | null; summary: string | null
  recommendation: { primary_issue?: string | null; steps: string[]; escalation_reason?: string | null } | null
  validation: { outcome: string | null; agreement_pct: number | null; requires_review: boolean }
  suggested_response: { text: string | null; guard_status: string; version: number } | null
  escalation_warnings: string[]; due_at: string | null
}
export interface AgentWorkspace {
  scope: 'mine' | 'all'; team: string | null
  counts: { total: number; assigned_to_me: number; with_warnings: number; needs_review: number; without_reply: number }
  complaints: AgentItem[]
}

export const complaints = {
  list: (f?: ComplaintFilters) => apiFetch<Page<S['ComplaintSummary']>>(`/api/complaints${qs(f)}`),
  mine: (page = 1, size = 20) => apiFetch<Page<S['ComplaintStatusOut']>>(`/api/complaints/mine${qs({ page, size })}`),
  create: (data: S['ComplaintCreate'], analyse = true) =>
    apiFetch<S['IntakeResponse']>(`/api/complaints${qs({ analyse })}`, { method: 'POST', body: data }),
  get: (ref: string) => apiFetch<S['ComplaintDetail']>(`/api/complaints/${enc(ref)}`),
  explain: (ref: string) => apiFetch<S['ExplainResponse']>(`/api/complaints/${enc(ref)}/explain`),
  reanalyse: (ref: string, run_genai = true) =>
    apiFetch<S['ReanalyseResponse']>(`/api/complaints/${enc(ref)}/reanalyse${qs({ run_genai })}`, { method: 'POST' }),
  status: (ref: string) => apiFetch<S['ComplaintStatusOut']>(`/api/complaints/${enc(ref)}/status`),
  changeStatus: (ref: string, to_status: string, reason?: string) =>
    apiFetch<S['LifecycleOut']>(`/api/complaints/${enc(ref)}/status`, { method: 'POST', body: { to_status, reason } }),
  checklist: (ref: string) => apiFetch<S['ChecklistOut']>(`/api/complaints/${enc(ref)}/checklist`),
  confirmStep: (ref: string, stepId: string) =>
    apiFetch<S['ChecklistOut']>(`/api/complaints/${enc(ref)}/checklist/${enc(stepId)}/confirm`, { method: 'POST' }),
  followUps: (ref: string) => apiFetch<S['FollowUpOut'][]>(`/api/complaints/${enc(ref)}/follow-ups`),
  completeFollowUp: (ref: string, id: string) =>
    apiFetch<S['FollowUpOut'][]>(`/api/complaints/${enc(ref)}/follow-ups/${enc(id)}/complete`, { method: 'POST' }),
  escalation: (ref: string) => apiFetch<S['schemas__complaints__EscalationOut']>(`/api/complaints/${enc(ref)}/escalation`),
  lifecycle: (ref: string) => apiFetch<S['LifecycleOut']>(`/api/complaints/${enc(ref)}/lifecycle`),
  responses: (ref: string) => apiFetch<ResponseDraft[]>(`/api/complaints/${enc(ref)}/responses`),
  draftResponse: (ref: string) => apiFetch<ResponseDraft>(`/api/complaints/${enc(ref)}/responses`, { method: 'POST' }),

  /* ── what the customer can do after submitting ── */
  answer: (ref: string, questionId: string, answer: string) =>
    apiFetch<S['ClarificationAnswerOut']>(
      `/api/complaints/${enc(ref)}/clarifications/${enc(questionId)}/answer`,
      { method: 'POST', body: { answer } },
    ),
  /** Nothing is stored and no model is called; safe to run on every pause in typing. */
  preview: (title: string, description: string) =>
    apiFetch<S['PreviewOut']>('/api/complaints/preview', { method: 'POST', body: { title, description } }),
  uploadEvidence: (ref: string, file: File, onProgress?: (fraction: number) => void) =>
    uploadWithProgress<S['EvidenceOut']>(`/api/complaints/${enc(ref)}/evidence`, file, onProgress),
  /** Fetched with the bearer header and saved as a blob; the token never goes in a URL. */
  downloadEvidence: async (ref: string, evidenceId: string, fileName: string) => {
    const res = await apiFetch<Response>(`/api/complaints/${enc(ref)}/evidence/${enc(evidenceId)}`, { raw: true })
    const url = URL.createObjectURL(await res.blob())
    const a = document.createElement('a')
    a.href = url
    a.download = fileName
    a.click()
    URL.revokeObjectURL(url)
  },
}

/* ------------------------------------------------------------------ review */

export const review = {
  queue: (f?: { page?: number; size?: number; status?: string; assigned_to_me?: boolean; breached_only?: boolean }) =>
    apiFetch<Page<S['ReviewItemOut']>>(`/api/review/queue${qs(f)}`),
  stats: () => apiFetch<S['QueueStatsOut']>('/api/review/stats'),
  claim: (ref: string) => apiFetch<S['ReviewItemOut']>(`/api/review/queue/${enc(ref)}/claim`, { method: 'POST' }),
  act: (ref: string, body: S['ReviewActionRequest']) =>
    apiFetch<S['ReviewActionOut']>(`/api/review/${enc(ref)}/actions`, { method: 'POST', body }),
  history: (ref: string) => apiFetch<S['ReviewHistoryOut'][]>(`/api/review/${enc(ref)}/history`),
  sla: (ref: string) => apiFetch<S['SLAStatusOut'][]>(`/api/review/${enc(ref)}/sla`),
  sweep: (limit?: number) => apiFetch<S['SLASweepOut']>(`/api/review/sla/sweep${qs({ limit })}`, { method: 'POST' }),
  dueFollowUps: (limit = 100) => apiFetch<S['DueFollowUpOut'][]>(`/api/review/follow-ups/due${qs({ limit })}`),
}

/* ------------------------------------------------------------------ analytics */

export interface ReportFilters {
  limit?: number; mismatches_only?: boolean; breached_only?: boolean; overrides_only?: boolean
  unresolved_only?: boolean; status?: string; dataset_tag?: string; field?: string
}

export const analytics = {
  dashboard: (days?: number) => apiFetch<S['DashboardOut']>(`/api/analytics/dashboard${qs({ days })}`),
  volume: (days?: number) => apiFetch<VolumeSeries>(`/api/analytics/volume${qs({ days })}`),
  categories: (days?: number) => apiFetch<S['CategorySliceOut'][]>(`/api/analytics/categories${qs({ days })}`),
  departments: (days?: number) => apiFetch<S['DepartmentLoadOut'][]>(`/api/analytics/departments${qs({ days })}`),
  pipelines: (days?: number) => apiFetch<S['PipelineOut']>(`/api/analytics/pipelines${qs({ days })}`),
  trends: (period?: string) => apiFetch<S['TrendOut'][]>(`/api/analytics/trends${qs({ period })}`),
  snapshotTrends: (period?: string) =>
    apiFetch<Record<string, unknown>>(`/api/analytics/trends/snapshot${qs({ period })}`, { method: 'POST' }),
  trendHistory: (metric: string, dimension_value?: string, limit?: number) =>
    apiFetch<S['TrendSnapshotOut'][]>(`/api/analytics/trends/history${qs({ metric, dimension_value, limit })}`),
  reports: () => apiFetch<S['ReportTypeOut'][]>('/api/analytics/reports'),
  report: (type: string, f?: ReportFilters) => apiFetch<S['ReportOut']>(`/api/analytics/reports/${enc(type)}${qs(f)}`),
  /** Downloads through fetch so the bearer token stays in a header, never in a URL. */
  exportReport: async (type: string, format: 'csv' | 'json', f?: ReportFilters) => {
    const res = await apiFetch<Response>(`/api/analytics/reports/${enc(type)}/export${qs({ format, ...f })}`, { raw: true })
    const blob = await res.blob()
    const name = res.headers.get('content-disposition')?.match(/filename="?([^"]+)"?/)?.[1] ?? `${type}.${format}`
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = name
    a.click()
    URL.revokeObjectURL(url)
    return name
  },
  exports: (limit?: number) => apiFetch<S['ExportHistoryOut'][]>(`/api/analytics/exports${qs({ limit })}`),
  myQueue: () => apiFetch<MyQueue>('/api/analytics/my-queue'),
  /** The agent dashboard: assigned/team complaints with recommendation, validation, reply and warnings. */
  agentWorkspace: (department?: string) => apiFetch<AgentWorkspace>(`/api/analytics/agent-workspace${qs({ department })}`),
}

/* ------------------------------------------------------------------ knowledge base */

export const knowledge = {
  list: (f?: { q?: string; doc_type?: string; status?: string; page?: number; page_size?: number }) =>
    apiFetch<Page<S['DocumentSummary']>>(`/api/documents${qs(f)}`),
  upload: (files: File[], opts?: { department_code?: string; activate?: boolean }) => {
    const form = new FormData()
    files.forEach((f) => form.append('files', f))
    return apiFetch<S['UploadResponse']>(`/api/documents${qs(opts)}`, { method: 'POST', body: form })
  },
  coverage: () => apiFetch<S['CoverageResponse']>('/api/documents/coverage'),
  validationIssues: (f?: { issue_code?: string; outcome?: string; page?: number; page_size?: number }) =>
    apiFetch<Page<S['schemas__documents__ValidationIssueOut']>>(`/api/documents/validation-issues${qs(f)}`),
  get: (id: string) => apiFetch<S['DocumentDetail']>(`/api/documents/${enc(id)}`),
  version: (id: string) => apiFetch<S['DocumentVersionDetail']>(`/api/documents/versions/${enc(id)}`),
  chunks: (id: string) => apiFetch<S['RetrievedChunkOut'][]>(`/api/documents/versions/${enc(id)}/chunks`),
  activate: (id: string) => apiFetch<S['ActivationResponse']>(`/api/documents/versions/${enc(id)}/activate`, { method: 'POST' }),
  deactivate: (id: string) => apiFetch<S['ActivationResponse']>(`/api/documents/versions/${enc(id)}/deactivate`, { method: 'POST' }),
  impact: (id: string) => apiFetch<S['PolicyImpactOut']>(`/api/documents/versions/${enc(id)}/impact`),
  search: (body: S['SearchRequest']) => apiFetch<S['SearchResponse']>('/api/documents/search', { method: 'POST', body }),
  trace: (chunkKey: string) => apiFetch<S['TraceabilityResponse']>(`/api/documents/trace/${enc(chunkKey)}`),
  byReference: (doc_ref: string, section_ref?: string) =>
    apiFetch<S['TraceabilityResponse']>(`/api/documents/chunks/by-reference${qs({ doc_ref, section_ref })}`),
}

/* ------------------------------------------------------------------ benchmark */

export const benchmark = {
  datasets: () => apiFetch<S['DatasetOut'][]>('/api/benchmark/datasets'),
  dataset: (tag: string) => apiFetch<S['DatasetOut']>(`/api/benchmark/datasets/${enc(tag)}`),
  deleteDataset: (tag: string) => apiFetch<Record<string, number | string>>(`/api/benchmark/datasets/${enc(tag)}`, { method: 'DELETE' }),
  importDataset: (tag: string, file: File, replace = false) => {
    const form = new FormData()
    form.append('file', file)
    return apiFetch<S['ImportResultOut']>(`/api/benchmark/datasets/${enc(tag)}/import${qs({ replace })}`, { method: 'POST', body: form })
  },
  run: (p: { dataset_tag: string; label?: string; limit?: number; run_genai?: boolean; workers?: number; resume?: boolean }) =>
    apiFetch<S['BenchmarkRunOut']>(`/api/benchmark/run${qs(p)}`, { method: 'POST' }),
  runs: (limit?: number) => apiFetch<S['BenchmarkRunOut'][]>(`/api/benchmark/runs${qs({ limit })}`),
  runDetail: (id: string) => apiFetch<S['BenchmarkDetailOut']>(`/api/benchmark/runs/${enc(id)}`),
}

/* ------------------------------------------------------------------ admin */

export const admin = {
  config: () => apiFetch<S['ConfigEntryOut'][]>('/api/admin/config'),
  updateConfig: (key: string, value: unknown, reason?: string) =>
    apiFetch<S['ConfigEntryOut']>(`/api/admin/config/${enc(key)}`, { method: 'PUT', body: { value, reason } }),
  taxonomy: () => apiFetch<S['TaxonomyOut']>('/api/admin/taxonomy'),
  rules: (f?: { rule_type?: string; active?: boolean; mandatory?: boolean; search?: string }) =>
    apiFetch<S['RuleSummaryOut'][]>(`/api/admin/rules${qs(f)}`),
  rule: (ref: string) => apiFetch<S['RuleDetailOut']>(`/api/admin/rules/${enc(ref)}`),
  updateRule: (ref: string, body: S['RuleUpdateIn']) =>
    apiFetch<S['RuleChangeOut']>(`/api/admin/rules/${enc(ref)}`, { method: 'PATCH', body }),
  testRules: (body: S['RuleTestIn']) => apiFetch<S['RuleTestOut']>('/api/admin/rules/test', { method: 'POST', body }),
  reloadRules: () => apiFetch<S['ReloadOut']>('/api/admin/rules/reload', { method: 'POST' }),
  lexicon: (signal_key?: string) => apiFetch<S['LexiconTermOut'][]>(`/api/admin/lexicon${qs({ signal_key })}`),
  addTerm: (body: S['LexiconTermIn']) => apiFetch<S['LexiconTermOut']>('/api/admin/lexicon', { method: 'POST', body }),
  editTerm: (id: string, body: S['LexiconTermUpdateIn']) =>
    apiFetch<S['LexiconTermOut']>(`/api/admin/lexicon/${enc(id)}`, { method: 'PATCH', body }),
  removeTerm: (id: string) => apiFetch<S['LexiconTermOut']>(`/api/admin/lexicon/${enc(id)}`, { method: 'DELETE' }),
  sla: () => apiFetch<S['SLAPolicyOut'][]>('/api/admin/sla'),
  updateSla: (id: string, body: S['SLAPolicyUpdateIn']) =>
    apiFetch<S['SLAPolicyOut']>(`/api/admin/sla/${enc(id)}`, { method: 'PATCH', body }),
  prompts: () => apiFetch<S['PromptVersionOut'][]>('/api/admin/prompts'),
  activatePrompt: (name: string, version: string, reason?: string) =>
    apiFetch<S['PromptVersionOut']>(`/api/admin/prompts/${enc(name)}`, { method: 'PATCH', body: { version, reason } }),
  defects: () => apiFetch<S['DefectSpecOut'][]>('/api/admin/defects'),
  demonstrateAll: () => apiFetch<S['DefectResultOut'][]>('/api/admin/defects/demonstrate', { method: 'POST' }),
  demonstrate: (code: string) => apiFetch<S['DefectResultOut']>(`/api/admin/defects/${enc(code)}/demonstrate`, { method: 'POST' }),
}

/* ------------------------------------------------------------------ audit */

/** The support mailbox: what arrived, what was answered, and a way to test without Gmail. */
export const mail = {
  status: () => apiFetch<Record<string, unknown> & { address: string | null; receiving: boolean; sending: string | null; resend_key_present: boolean; last_poll_at: string | null; last_error: string | null }>('/api/email/status'),
  messages: (f?: { direction?: 'IN' | 'OUT'; intent?: string; page?: number; size?: number }) => apiFetch<Page<S['EmailOut']>>(`/api/email/messages${qs(f)}`),
  message: (id: string) => apiFetch<S['EmailDetail']>(`/api/email/messages/${enc(id)}`),
  poll: () => apiFetch<Record<string, unknown>>('/api/email/poll', { method: 'POST' }),
  simulate: (body: S['SimulateIn']) => apiFetch<S['EmailDetail']>('/api/email/simulate', { method: 'POST', body }),
  preview: () => apiFetch<{ html: string }>('/api/email/preview'),
}

/** Nova, the chat receptionist. It only talks; filing goes through complaints.stream. */
export const assistant = {
  chat: (messages: Array<{ role: 'user' | 'assistant'; content: string }>) =>
    apiFetch<S['ChatOut']>('/api/assistant/chat', { method: 'POST', body: { messages } }),
}

/** The organisation the dataset defines: profile, teams, taxonomy, SLAs, templates. */
export const organisation = {
  get: () => apiFetch<S['OrganisationOut']>('/api/organisation'),
}

export const audit = {
  list: (f?: { page?: number; size?: number; entity_type?: string; action?: string; actor?: string; entity_id?: string }) =>
    apiFetch<Page<S['AuditEntryOut']>>(`/api/audit${qs(f)}`),
  actions: () => apiFetch<S['AuditActionCountOut'][]>('/api/audit/actions'),
  trail: (entityType: string, entityId: string) =>
    apiFetch<S['AuditEntryOut'][]>(`/api/audit/${enc(entityType)}/${enc(entityId)}`),
}
